# .github/workflows/deploy-backend.yml

name: Deploy Backend

on:
  push:
    paths:
      - 'apps/backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      HUSKY: 0 # disables husky hooks
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install backend dependencies only
        run: npm install --workspace apps/backend

      - name: Set up backend environment variables
        working-directory: apps/backend
        run: |
          touch .env
          echo "${{ secrets.BACKEND_ENV }}" > .env

      - name: Build backend
        working-directory: apps/backend
        run: npm run build

      - name: Restart backend with PM2
        working-directory: apps/backend
        run: |
          pm2 restart backend || pm2 start dist/index.js --name backend
